version: "3.3"
services:

  # api:
  #   image: creation_station_api:latest
  #   build:
  #     context: .
  #     dockerfile: config/api.Dockerfile
  #   ports:
  #     - "5000:5000"

  web:
    image: creation_station_web:latest
    build:
      context: .
      dockerfile: config/web.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/client:/web
      # - ./src/client/node_modules:/web/node_modules
