version: "3.3"
services:

  api:
    image: creation-station-api:latest
    build:
      context: .
      dockerfile: config/api.Dockerfile
    ports:
      - "5000:5000"
    deploy:
      restart_policy:
        condition: on-failure
