version: "3.3"
services:

  api:
    image: creation_station_api:latest
    build:
      context: ./src/server
      dockerfile: ../../config/api.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src/server:/api
    restart: always

  web:
    image: creation_station_web:latest
    build:
      context: ./src/client
      dockerfile: ../../config/web.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/client:/web
    restart: always
