version: 2

jobs:
  build:
    working_directory: ~/project

    docker:
      - image: circleci/python:3.8.0-buster

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: 'Build'
          command: |
            sudo apt-get -y -qq install ffmpeg
            mkdir reports
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: 'Test'
          command: |
            . venv/bin/activate
            python -m pytest -v --junitxml reports/junit.xml src/

      - run:
          name: 'Lint'
          command: |
            . venv/bin/activate
            flake8 ./src/ --max-line-length=160 --output-file reports/lint.txt

      - store_test_results:
          path: reports

      - store_artifacts:
          path: reports
          destination: tr1
