version: 2

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.8.0-buster
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: 'Build'
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: 'Test'
          command: |
            mkdir test-results
            . venv/bin/activate
            python -m pytest -v --junitxml test-results/junit.xml src/
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1